const queryKeys = {
  GET_DESIGNATION: "GET_DESIGNATION",
  GET_ALL_CLASSES: "GET_ALL_CLASSES",
  GET_ALL_CAMPUSES: "GET_ALL_CAMPUSES",
  GET_CAMPUS: "GET_CAMPUS",
  GET_ALL_STAFFS: "GET_ALL_STAFFS",
  GET_ALL_STUDENTS: "GET_ALL_STUDENTS",
};

export default queryKeys;
